### ISSUE TITLE
Versi IOS

### ISSUE THREAD

**Issue by infacq** [Akim95/sample-react-native-todo#1]
Salam bro, kenapa versi ios takda? tak ok ke? kena run `pod install` tak?

**Comment by Akim95** [comment]
W'salam, sebab lebih pakai komponen Android kat app ini. (cth: ToolbarAndroid)

**Comment by Akim95** [comment]
Tak perlu `pod install` boleh terus run `react-native run-ios` kalau nak cuba versi iOS tapi tak berapa berfungsi.

**Comment by infacq** [comment]
ohh patut la toolbar takda
